<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-EKTU0VS" failures="1" tests="1" name="Test2" time="55.804" errors="0" timestamp="09 May 2024 12:58:57 GMT">
  <testcase classname="com.comcast.crm.contesttest.CreateContactTest" name="createContactTest" time="3.631">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.comcast.crm.contesttest.CreateContactTest.createContactTest(CreateContactTest.java:55)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- createContactTest -->
  <testcase classname="com.comcast.crm.contesttest.CreateContactTest" name="CreateContactWithSupportDateTest" time="0.0">
    <ignored/>
  </testcase> <!-- CreateContactWithSupportDateTest -->
  <testcase classname="com.comcast.crm.contesttest.CreateContactTest" name="CreateContactWithOrgTest" time="0.0">
    <ignored/>
  </testcase> <!-- CreateContactWithOrgTest -->
</testsuite> <!-- Test2 -->
